### ISSUE TITLE
Add examples of using this library in Maven / Gradle to README

### ISSUE THREAD

**Issue by berry120** [quelea-projection/planning-center-java-api#1]
We should add maven / gradle snippets of how to include this library in your pom file (these can be retrieved from https://mvnrepository.com/artifact/org.quelea/planning-center/0.2).

This should be added to the main repository README file.

**Comment by sarthakvijay** [comment]
Hi @berry120, You want to attach the picture of the addition of this maven dependency in the pom.xml file and include it in the README.md file. 

Like the one attached below.

https://user-images.githubusercontent.com/20266451/135771468-7ae15876-df26-4144-b30c-5a1a6594e1e8.jpg

If that's the requirement, please assign the above issue to me under hacktoberfest, I would raise the PR for the same.

**Comment by berry120** [comment]
Sure! All yours.

We're not after a picture - just, as text, everything in the dependency tags (for the Maven part.)

See here for an (unrelated) example of the sort of thing we're after: https://github.com/berry120/AC500
